services:
  - type: web
    name: fahim-fashion
    runtime: php
    region: oregon
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: ""
    rootDir: .
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:your_generated_key_here
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: db4free.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db
      - key: DB_USERNAME
        value: your_user
      - key: DB_PASSWORD
        value: your_password
