services:
  - type: web
    name: fahim-fashion
    env: php
    buildCommand: "composer install"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:GENERATE_LATER
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite

prebuild:
  commands:
    - touch /tmp/database.sqlite
